"""Experimentation & Segmentation demo using DuckDB.

Runs A/B test analysis and K-Means user segmentation on the synthetic
data generated by infra-data-pipelines.

Usage:
    python demo.py --db ../infra-data-pipelines/demo.duckdb
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import duckdb
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Add repo root to path for imports
sys.path.insert(0, str(Path(__file__).parent))
from analysis.experiment_analyzer import ExperimentAnalyzer


# ── dbt-equivalent queries ──────────────────────────────────────────


def build_experiment_outcomes(con: duckdb.DuckDBPyConnection) -> pd.DataFrame:
    """Execute fct_experiment_outcomes logic."""
    sql = """
    WITH assignments AS (
        SELECT ea.member_id, ea.experiment_id, ea.variant,
               exp.experiment_name, exp.start_date, exp.end_date
        FROM raw.experiment_assignments ea
        JOIN raw.experiments exp ON exp.experiment_id = ea.experiment_id
    ),
    event_success AS (
        SELECT fe.member_id, fe.event_date::DATE AS event_date, fe.event_name
        FROM raw.feature_events fe
        WHERE fe.event_name IN ('onboarding_completed', 'health_goal_set')
    ),
    daily_filtered AS (
        SELECT dm.member_id, dm.metric_date::DATE AS metric_date,
               dm.hrv, dm.resting_heart_rate, dm.sleep_hours,
               dm.sleep_quality, dm.strain, dm.recovery
        FROM raw.daily_metrics dm
    ),
    aggregated AS (
        SELECT
            a.experiment_id, a.experiment_name, a.variant,
            COUNT(DISTINCT a.member_id) AS participants,
            COUNT(DISTINCT CASE
                WHEN es.member_id IS NOT NULL
                 AND es.event_date BETWEEN a.start_date AND a.end_date
                THEN a.member_id END) AS converters,
            AVG(CASE WHEN dm.metric_date BETWEEN a.start_date AND a.end_date
                     THEN dm.hrv END) AS avg_hrv,
            AVG(CASE WHEN dm.metric_date BETWEEN a.start_date AND a.end_date
                     THEN dm.strain END) AS avg_strain,
            AVG(CASE WHEN dm.metric_date BETWEEN a.start_date AND a.end_date
                     THEN dm.recovery END) AS avg_recovery,
            AVG(CASE WHEN dm.metric_date BETWEEN a.start_date AND a.end_date
                     THEN dm.sleep_hours END) AS avg_sleep_hours
        FROM assignments a
        LEFT JOIN event_success es ON es.member_id = a.member_id
        LEFT JOIN daily_filtered dm ON dm.member_id = a.member_id
        GROUP BY 1, 2, 3
    )
    SELECT *, converters * 1.0 / NULLIF(participants, 0) AS conversion_rate
    FROM aggregated
    ORDER BY experiment_id, variant
    """
    return con.execute(sql).df()


def build_health_kpis(con: duckdb.DuckDBPyConnection) -> pd.DataFrame:
    """Execute fct_health_kpis logic and aggregate to member level."""
    sql = """
    SELECT
        member_id,
        AVG(hrv) AS avg_hrv,
        AVG(strain) AS avg_strain,
        AVG(recovery) AS avg_recovery,
        AVG(sleep_hours) AS avg_sleep_hours,
        AVG(sleep_quality) AS avg_sleep_quality,
        AVG(resting_heart_rate) AS avg_resting_hr,
        COUNT(*) AS days_active
    FROM raw.daily_metrics
    GROUP BY member_id
    """
    return con.execute(sql).df()


# ── A/B Test Analysis ────────────────────────────────────────────────


def run_ab_analysis(outcomes_df: pd.DataFrame, out_dir: Path) -> None:
    """Analyze each experiment using the ExperimentAnalyzer."""
    analyzer = ExperimentAnalyzer(alpha=0.05)

    experiments = outcomes_df["experiment_id"].unique()
    for exp_id in sorted(experiments):
        exp_data = outcomes_df[outcomes_df["experiment_id"] == exp_id]
        exp_name = exp_data["experiment_name"].iloc[0]
        ctrl = exp_data[exp_data["variant"] == "control"].iloc[0]
        treat = exp_data[exp_data["variant"] == "treatment"].iloc[0]

        print(f"\n  Experiment {exp_id}: {exp_name}")
        print(f"  {'':4s}{'Variant':12s} {'Participants':>12s} {'Converters':>10s} {'Conv Rate':>10s} {'Avg HRV':>8s} {'Avg Strain':>10s}")
        for _, row in exp_data.iterrows():
            print(f"  {'':4s}{row['variant']:12s} {int(row['participants']):>12,} {int(row['converters']):>10,} "
                  f"{row['conversion_rate']:>10.3f} {row['avg_hrv']:>8.1f} {row['avg_strain']:>10.1f}")

        # Use conversion rate difference for statistical test
        # Simulate per-member binary outcomes for the t-test
        np.random.seed(int(exp_id))
        n_ctrl = int(ctrl["participants"])
        n_treat = int(treat["participants"])
        ctrl_outcomes = np.random.binomial(1, ctrl["conversion_rate"], n_ctrl).astype(float)
        treat_outcomes = np.random.binomial(1, treat["conversion_rate"], n_treat).astype(float)

        result = analyzer.analyze(ctrl_outcomes, treat_outcomes)
        print(f"\n  {'':4s}Decision:    {result.decision}")
        print(f"  {'':4s}p-value:     {result.p_value:.4f}")
        print(f"  {'':4s}Cohen's d:   {result.cohen_d:.4f}")
        print(f"  {'':4s}95% CI:      [{result.ci_low:.4f}, {result.ci_high:.4f}]")

    # Plot: conversion rate comparison for all experiments
    fig, axes = plt.subplots(1, len(experiments), figsize=(7 * len(experiments), 6))
    if len(experiments) == 1:
        axes = [axes]

    colors = {"control": "#4878CF", "treatment": "#6ACC65"}
    for i, exp_id in enumerate(sorted(experiments)):
        exp_data = outcomes_df[outcomes_df["experiment_id"] == exp_id]
        exp_name = exp_data["experiment_name"].iloc[0]
        ax = axes[i]
        variants = exp_data["variant"].tolist()
        rates = exp_data["conversion_rate"].tolist()
        bars = ax.bar(variants, rates, color=[colors.get(v, "#999") for v in variants], alpha=0.8)
        ax.set_title(f"Experiment {exp_id}: {exp_name}")
        ax.set_ylabel("Conversion Rate")
        ax.yaxis.set_major_formatter(mticker.PercentFormatter(1.0))
        ax.set_ylim(0, max(rates) * 1.3)
        for bar, rate in zip(bars, rates):
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
                    f"{rate:.1%}", ha="center", va="bottom", fontsize=11)
        ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    path = out_dir / "ab_test_results.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\n  Saved {path}")


# ── K-Means Segmentation ────────────────────────────────────────────


def run_segmentation(kpis_df: pd.DataFrame, out_dir: Path) -> None:
    """Cluster members into behavioral segments."""
    features = ["avg_hrv", "avg_strain", "avg_recovery", "avg_sleep_hours", "avg_sleep_quality"]
    X = kpis_df[features].dropna()

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Elbow method
    inertias = []
    K_range = range(2, 8)
    for k in K_range:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        km.fit(X_scaled)
        inertias.append(km.inertia_)

    # Run with k=3
    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
    kpis_df = kpis_df.loc[X.index].copy()
    kpis_df["cluster"] = kmeans.fit_predict(X_scaled)

    # Name clusters by avg strain
    cluster_means = kpis_df.groupby("cluster")[features].mean()
    strain_rank = cluster_means["avg_strain"].rank(ascending=False).astype(int)
    name_map = {}
    for c, rank in strain_rank.items():
        if rank == 1:
            name_map[c] = "Power"
        elif rank == 2:
            name_map[c] = "Active"
        else:
            name_map[c] = "Casual"
    kpis_df["segment"] = kpis_df["cluster"].map(name_map)

    print(f"\n  Segment Profiles:")
    seg_profile = kpis_df.groupby("segment")[features].mean().round(1)
    seg_counts = kpis_df["segment"].value_counts()
    for seg in ["Power", "Active", "Casual"]:
        if seg in seg_profile.index:
            row = seg_profile.loc[seg]
            print(f"    {seg:8s} (n={seg_counts[seg]:,}):  HRV={row['avg_hrv']:.1f}  "
                  f"Strain={row['avg_strain']:.1f}  Recovery={row['avg_recovery']:.1f}  "
                  f"Sleep={row['avg_sleep_hours']:.1f}h  Quality={row['avg_sleep_quality']:.1f}")

    # ── Plot 1: Elbow ──
    fig_elbow, ax_elbow = plt.subplots(figsize=(8, 4))
    ax_elbow.plot(list(K_range), inertias, "bo-", linewidth=2)
    ax_elbow.axvline(x=3, color="red", linestyle="--", alpha=0.5, label="k=3 selected")
    ax_elbow.set_xlabel("Number of Clusters (k)")
    ax_elbow.set_ylabel("Inertia")
    ax_elbow.set_title("Elbow Method for Optimal k")
    ax_elbow.legend()
    ax_elbow.grid(True, alpha=0.3)
    path = out_dir / "elbow_plot.png"
    fig_elbow.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig_elbow)
    print(f"  Saved {path}")

    # ── Plot 2: Scatter + Radar ──
    colors = {"Power": "#2ecc71", "Active": "#3498db", "Casual": "#e74c3c"}
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))

    # Scatter: HRV vs Strain
    for seg in ["Power", "Active", "Casual"]:
        subset = kpis_df[kpis_df["segment"] == seg]
        axes[0].scatter(subset["avg_hrv"], subset["avg_strain"],
                        alpha=0.3, label=f"{seg} (n={len(subset):,})",
                        color=colors[seg], s=15)
    axes[0].set_xlabel("Average HRV")
    axes[0].set_ylabel("Average Strain")
    axes[0].set_title("Member Segments: HRV vs Strain")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Radar chart
    seg_means = kpis_df.groupby("segment")[features].mean()
    seg_norm = (seg_means - seg_means.min()) / (seg_means.max() - seg_means.min() + 1e-8)
    angles = np.linspace(0, 2 * np.pi, len(features), endpoint=False).tolist()
    angles += angles[:1]
    feature_labels = ["HRV", "Strain", "Recovery", "Sleep Hrs", "Sleep Qual"]

    ax_radar = fig.add_subplot(122, polar=True)
    axes[1].set_visible(False)
    for seg in ["Power", "Active", "Casual"]:
        vals = seg_norm.loc[seg].tolist() + [seg_norm.loc[seg].tolist()[0]]
        ax_radar.plot(angles, vals, "o-", label=seg, color=colors[seg], linewidth=2)
        ax_radar.fill(angles, vals, alpha=0.1, color=colors[seg])
    ax_radar.set_xticks(angles[:-1])
    ax_radar.set_xticklabels(feature_labels, size=9)
    ax_radar.set_title("Segment Profiles (Normalized)", y=1.08)
    ax_radar.legend(loc="upper right", bbox_to_anchor=(1.35, 1.1))

    plt.tight_layout()
    path = out_dir / "segmentation_results.png"
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {path}")


# ── Main ─────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Experimentation & Segmentation Demo")
    parser.add_argument("--db", type=str, default="../infra-data-pipelines/demo.duckdb",
                        help="Path to DuckDB database from infra repo")
    args = parser.parse_args()

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"Database not found at {db_path}")
        print("Run the infra-data-pipelines demo first: cd ../infra-data-pipelines && python demo.py")
        return

    con = duckdb.connect(str(db_path), read_only=True)
    out_dir = Path(__file__).parent / "screenshots"
    out_dir.mkdir(exist_ok=True)

    # Run tests first
    print("=" * 60)
    print("  STEP 1: Running pytest on ExperimentAnalyzer")
    print("=" * 60)
    import subprocess
    test_result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-v", "--tb=short"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent)
    )
    print(test_result.stdout)
    if test_result.returncode != 0:
        print(test_result.stderr)
        print("Tests failed. Fix before continuing.")
        return

    # A/B Test Analysis
    print("=" * 60)
    print("  STEP 2: A/B Test Analysis")
    print("=" * 60)
    print("\nBuilding fct_experiment_outcomes...")
    outcomes_df = build_experiment_outcomes(con)
    print(f"  {len(outcomes_df)} rows")
    run_ab_analysis(outcomes_df, out_dir)

    # Segmentation
    print("\n" + "=" * 60)
    print("  STEP 3: K-Means Segmentation")
    print("=" * 60)
    print("\nBuilding member-level health KPIs...")
    kpis_df = build_health_kpis(con)
    print(f"  {len(kpis_df):,} members")
    run_segmentation(kpis_df, out_dir)

    con.close()
    print(f"\n{'='*60}")
    print(f"  DEMO COMPLETE")
    print(f"  Charts: {out_dir}/")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
